require('nvim-treesitter.configs').setup {
    ensure_installed = {
        'apex',
        'bash',
        'css',
        'haskell',
        'html',
        'java',
        'javascript',
        'json',
        'lua',
        'markdown',
        'markdown_inline',
        'python',
        'sflog',
        'soql',
        'sosl',
        'vim',
    },
    sync_install = false,
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
